<a href="https://colab.research.google.com/github/Harikaraja/BMI_from_facil_images/blob/main/BMI_To_Facial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import cv2
from sklearn import model_selection
import tensorflow as tf
from tensorflow import keras
from keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
from keras.models import Sequential

**Data Set Loaidng**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
path = "/content/drive/MyDrive/Deep Learning projects/BMI.csv"

Mounted at /content/drive


In [ ]:
df = pd.read_csv(path,usecols=['Sr.no.', 'BMI']).values
print(df)

[[1.00000000e+00 2.56800741e+01]
 [2.00000000e+00 2.38884410e+01]
 [3.00000000e+00 2.52077562e+01]
 ...
 [5.36500000e+03 1.67276859e+01]
 [5.36600000e+03 2.71604938e+01]
 [5.36700000e+03 2.21453287e+01]]


**Data Preprocessing**

In [ ]:
photo_path='/content/drive/MyDrive/Deep Learning projects/photos/'

In [ ]:
X = []  # the features, or inputs
y = []  # the labels, or outputs


for row in df:
  #print(row[0])
  path = str(int(row[0])) + '.jpg'
  print(path)
  image_bmi = float(row[1])
  image = load_img(photo_path + path, target_size=(128, 128))
  input_arr = img_to_array(image)
  input_arr = np.array(input_arr)
  X.append(input_arr)
  y.append(image_bmi)



Streaming output truncated to the last 5000 lines.
368.jpg
369.jpg
370.jpg
371.jpg
372.jpg
373.jpg
374.jpg
375.jpg
376.jpg
377.jpg
378.jpg
379.jpg
380.jpg
381.jpg
382.jpg
383.jpg
384.jpg
385.jpg
386.jpg
387.jpg
388.jpg
389.jpg
390.jpg
391.jpg
392.jpg
393.jpg
394.jpg
395.jpg
396.jpg
397.jpg
398.jpg
399.jpg
400.jpg
401.jpg
402.jpg
403.jpg
404.jpg
405.jpg
406.jpg
407.jpg
408.jpg
409.jpg
410.jpg
411.jpg
412.jpg
413.jpg
414.jpg
415.jpg
416.jpg
417.jpg
418.jpg
419.jpg
420.jpg
421.jpg
422.jpg
423.jpg
424.jpg
425.jpg
426.jpg
427.jpg
428.jpg
429.jpg
430.jpg
431.jpg
432.jpg
433.jpg
434.jpg
435.jpg
436.jpg
437.jpg
438.jpg
439.jpg
440.jpg
441.jpg
442.jpg
443.jpg
444.jpg
445.jpg
446.jpg
447.jpg
448.jpg
449.jpg
450.jpg
451.jpg
452.jpg
453.jpg
454.jpg
455.jpg
456.jpg
457.jpg
458.jpg
459.jpg
460.jpg
461.jpg
462.jpg
463.jpg
464.jpg
465.jpg
466.jpg
467.jpg
468.jpg
469.jpg
470.jpg
471.jpg
472.jpg
473.jpg
474.jpg
475.jpg
476.jpg
477.jpg
478.jpg
479.jpg
480.jpg
481.jpg
482.jpg
483.jpg
484.jpg
485.jpg
486.j

In [ ]:
print(X[1])
print(y)

[[[136. 100.  76.]
  [136. 100.  76.]
  [136. 100.  76.]
  ...
  [217. 207. 205.]
  [217. 207. 205.]
  [217. 207. 205.]]

 [[138. 102.  78.]
  [138. 102.  78.]
  [138. 102.  78.]
  ...
  [218. 208. 206.]
  [218. 208. 206.]
  [218. 208. 206.]]

 [[138. 102.  78.]
  [138. 102.  78.]
  [138. 102.  78.]
  ...
  [219. 209. 207.]
  [219. 209. 207.]
  [219. 209. 207.]]

 ...

 [[ 46.  46.  48.]
  [ 46.  46.  48.]
  [ 46.  46.  48.]
  ...
  [ 43.  42.  47.]
  [ 44.  43.  48.]
  [ 44.  43.  48.]]

 [[ 45.  45.  47.]
  [ 45.  45.  47.]
  [ 45.  45.  47.]
  ...
  [ 45.  44.  49.]
  [ 43.  42.  47.]
  [ 43.  42.  47.]]

 [[ 45.  45.  47.]
  [ 45.  45.  47.]
  [ 45.  45.  47.]
  ...
  [ 46.  45.  50.]
  [ 44.  43.  48.]
  [ 43.  42.  47.]]]
[25.68007405, 23.88844098, 25.20775623, 19.80534178, 22.265625, 30.71636818, 24.28026361, 26.27728508, 32.55769415, 21.46915048, 26.8744961, 28.29334541, 18.42403628, 19.10009183, 26.2345679, 17.30612245, 21.484375, 25.05930703, 18.31425598, 20.04744562, 17.9012

In [ ]:
print(y)

[25.68007405, 23.88844098, 25.20775623, 19.80534178, 22.265625, 30.71636818, 24.28026361, 26.27728508, 32.55769415, 21.46915048, 26.8744961, 28.29334541, 18.42403628, 19.10009183, 26.2345679, 17.30612245, 21.484375, 25.05930703, 18.31425598, 20.04744562, 17.90123457, 26.20786721, 21.98989237, 20.28479857, 27.75510204, 18.71094925, 30.47721924, 18.68512111, 18.68512111, 21.383942, 19.57168128, 24.25127831, 20.89795918, 18.93877551, 22.85714286, 19.83471074, 18.62138619, 20.57142857, 21.10726644, 22.32142857, 18.30576947, 25.15315023, 24.02127599, 22.20408163, 21.70792339, 19.70553242, 21.67125803, 21.50188649, 22.0603538, 29.70801268, 21.0076678, 30.45776225, 26.51180407, 25.05930703, 24.07407407, 21.55102041, 23.183391, 23.183391, 28.45713979, 27.16161159, 18.90690102, 19.57168128, 21.90758246, 22.37567995, 20.38156971, 17.63085399, 17.55561939, 19.53125, 18.80920625, 17.90123457, 20.38156971, 21.09619051, 23.20054323, 24.61810377, 24.81632653, 23.88844098, 26.58420139, 25.96454217, 24

In [ ]:
print(len(y))

5367


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [ ]:
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

In [ ]:
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

3220
2147
3220
2147


In [ ]:
from tensorflow.keras.layers import Input,Lambda,Dense,Flatten,GlobalAveragePooling2D
from tensorflow.keras.models import Model
from keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img


In [ ]:
IMAGE_SIZE = [128,128]


In [ ]:
base_model = VGG16(input_shape=IMAGE_SIZE + [3], weights = 'imagenet' ,include_top=False)

58889256/58889256 [==============================] - 2s 0us/step


In [ ]:
# Add Global Average Pooling layer
x = GlobalAveragePooling2D()(base_model.output)

In [ ]:
# Add a custom regression output layer
regression_layer = Dense(1, activation='linear')(x)

In [ ]:
for layer in base_model.layers:            # retraining of weights is not necessary because we are using state of art model
  layer.trainable = False

In [ ]:
# Create the new model
model = Model(inputs=base_model.input, outputs=regression_layer)

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 128, 128, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 128, 128, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 128, 128, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 64, 64, 64)        0         
                                                                 
 block2_conv1 (Conv2D)       (None, 64, 64, 128)       73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 64, 64, 128)       147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 32, 32, 128)       0     

In [ ]:
# Compile the model with an appropriate regression loss function (e.g., Mean Squared Error)
model.compile(optimizer='adam', loss='mean_squared_error',metrics=['accuracy'])

In [ ]:
epochs = 50
batch_size = 32
history = model.fit(X_train,y_train,epochs=epochs, batch_size=batch_size)

Epoch 1/50
101/101 [==============================] - 5s 46ms/step - loss: 54.7969 - accuracy: 0.0000e+00
Epoch 2/50
101/101 [==============================] - 5s 48ms/step - loss: 39.2556 - accuracy: 0.0000e+00
Epoch 3/50
101/101 [==============================] - 5s 49ms/step - loss: 31.5963 - accuracy: 0.0000e+00
Epoch 4/50
101/101 [==============================] - 5s 46ms/step - loss: 27.2670 - accuracy: 0.0000e+00
Epoch 5/50
101/101 [==============================] - 5s 47ms/step - loss: 23.7544 - accuracy: 0.0000e+00
Epoch 6/50
101/101 [==============================] - 5s 51ms/step - loss: 21.6802 - accuracy: 0.0000e+00
Epoch 7/50
101/101 [==============================] - 5s 50ms/step - loss: 20.0470 - accuracy: 0.0000e+00
Epoch 8/50
101/101 [==============================] - 5s 47ms/step - loss: 19.0915 - accuracy: 0.0000e+00
Epoch 9/50
101/101 [==============================] - 5s 46ms/step - loss: 18.0706 - accuracy: 0.0000e+00
Epoch 10/50
101/101 [=========================

In [ ]:
# Save the model
model.save('/content/drive/MyDrive/Deep Learning projects/model.h5')


**Evaluating the model based on imported model without X_train,y_train**

In [ ]:
X = np.array(X)
y = np.array(y)

In [ ]:
#finding metrics without training the model
results = model.evaluate(X, y)
print(results)

# Print the results
print("Mean Squared Error:", results[0])
#print("Accuracy:", results[1])


168/168 [==============================] - 8s 45ms/step - loss: 469.6210 - accuracy: 0.0000e+00
[469.6210021972656, 0.0]
Mean Squared Error: 469.6210021972656


In [ ]:
from sklearn.metrics import r2_score

# Assuming you have predictions for your test set
y_pred = model.predict(X_test)

# Calculate R^2 score
r2 = r2_score(y_test, y_pred)

# Print the R^2 score
print("R^2 Score:", r2)


34/34 [==============================] - 2s 43ms/step
R^2 Score: -43.37055862425291


**Evaluating the model after training with X_train and y_train**

In [ ]:
#finding metrics without training the model
results = model.evaluate(X_test, y_test)
print(results)

# Print the results
print("Mean Squared Error:", results[0])
#print("Accuracy:", results[1])


68/68 [==============================] - 3s 47ms/step - loss: 14.3236 - accuracy: 0.0000e+00
[14.323559761047363, 0.0]
Mean Squared Error: 14.323559761047363


In [ ]:
from sklearn.metrics import r2_score

# Assuming you have predictions for your test set
y_pred = model.predict(X_test)

# Calculate R^2 score
r2 = r2_score(y_test, y_pred)

# Print the R^2 score
print("R^2 Score:", r2)


68/68 [==============================] - 3s 41ms/step
R^2 Score: -0.3546938895049281


In [ ]:
# Save the model
model.save('/content/drive/MyDrive/Deep Learning projects/history.h5')
